const fs = require('fs');
const file = 'alfcomponents/enums/alf-color.enum.ts';
let content = fs.readFileSync(file, 'utf8');
const toInsert = `
  // ===== SOFT MODALITY =====
  PrimarySoft = 'var(--alf-primary-soft, #eff6ff)',
  PrimarySoftBorder = 'var(--alf-primary-soft-border, #dbeafe)',
  PrimarySoftBorderHover = 'var(--alf-primary-soft-border-hover, #bfdbfe)',
  PrimarySoftHover = 'var(--alf-primary-soft-hover, #eaf3fe)',
  PrimarySoftText = 'var(--alf-primary-soft-text, #5a9bfdff)',
  PrimarySoftTextHover = 'var(--alf-primary-soft-text-hover, #4085efff)',
  PrimarySoftFocus = 'var(--alf-primary-soft-focus, #4085ef40)',
  PrimarySoftDisabled = 'var(--alf-primary-soft-disabled, #c6d8f5)',
  PrimarySoftActive = 'var(--alf-primary-soft-active, #2d6fd440)',

  SecondarySoft = 'var(--alf-secondary-soft, #f8f9fa)',
  SecondarySoftBorder = 'var(--alf-secondary-soft-border, #e9ecef)',
  SecondarySoftBorderHover = 'var(--alf-secondary-soft-border-hover, #dee2e6)',
  SecondarySoftHover = 'var(--alf-secondary-soft-hover, #f4f5f7)',
  SecondarySoftText = 'var(--alf-secondary-soft-text, #8fa0b0ff)',
  SecondarySoftTextHover = 'var(--alf-secondary-soft-text-hover, #758797ff)',
  SecondarySoftFocus = 'var(--alf-secondary-soft-focus, #75879740)',
  SecondarySoftDisabled = 'var(--alf-secondary-soft-disabled, #d5d8da)',
  SecondarySoftActive = 'var(--alf-secondary-soft-active, #5d6e7e40)',

  SuccessSoft = 'var(--alf-success-soft, #f0fdf4)',
  SuccessSoftBorder = 'var(--alf-success-soft-border, #dcfce7)',
  SuccessSoftBorderHover = 'var(--alf-success-soft-border-hover, #bbf7d0)',
  SuccessSoftHover = 'var(--alf-success-soft-hover, #ebfcf0)',
  SuccessSoftText = 'var(--alf-success-soft-text, #6cbd97ff)',
  SuccessSoftTextHover = 'var(--alf-success-soft-text-hover, #57a882ff)',
  SuccessSoftFocus = 'var(--alf-success-soft-focus, #57a88240)',
  SuccessSoftDisabled = 'var(--alf-success-soft-disabled, #cae3d6)',
  SuccessSoftActive = 'var(--alf-success-soft-active, #43926c40)',

  DangerSoft = 'var(--alf-danger-soft, #fef2f2)',
  DangerSoftBorder = 'var(--alf-danger-soft-border, #fee2e2)',
  DangerSoftBorderHover = 'var(--alf-danger-soft-border-hover, #fecaca)',
  DangerSoftHover = 'var(--alf-danger-soft-hover, #feeeee)',
  DangerSoftText = 'var(--alf-danger-soft-text, #f67280ff)',
  DangerSoftTextHover = 'var(--alf-danger-soft-text-hover, #e25867ff)',
  DangerSoftFocus = 'var(--alf-danger-soft-focus, #e2586740)',
  DangerSoftDisabled = 'var(--alf-danger-soft-disabled, #f5ced2)',
  DangerSoftActive = 'var(--alf-danger-soft-active, #cb3f4e40)',

  WarningSoft = 'var(--alf-warning-soft, #fffbeb)',
  WarningSoftBorder = 'var(--alf-warning-soft-border, #fef3c7)',
  WarningSoftBorderHover = 'var(--alf-warning-soft-border-hover, #fde68a)',
  WarningSoftHover = 'var(--alf-warning-soft-hover, #fef9e2)',
  WarningSoftText = 'var(--alf-warning-soft-text, #f0b429ff)',
  WarningSoftTextHover = 'var(--alf-warning-soft-text-hover, #d99e16ff)',
  WarningSoftFocus = 'var(--alf-warning-soft-focus, #d99e1640)',
  WarningSoftDisabled = 'var(--alf-warning-soft-disabled, #fcedba)',
  WarningSoftActive = 'var(--alf-warning-soft-active, #b7820f40)',

  InfoSoft = 'var(--alf-info-soft, #ecfeff)',
  InfoSoftBorder = 'var(--alf-info-soft-border, #cffafe)',
  InfoSoftBorderHover = 'var(--alf-info-soft-border-hover, #a5f3fc)',
  InfoSoftHover = 'var(--alf-info-soft-hover, #e4fdfe)',
  InfoSoftText = 'var(--alf-info-soft-text, #4ec3deff)',
  InfoSoftTextHover = 'var(--alf-info-soft-text-hover, #35acc7ff)',
  InfoSoftFocus = 'var(--alf-info-soft-focus, #35acc740)',
  InfoSoftDisabled = 'var(--alf-info-soft-disabled, #c3f2fa)',
  InfoSoftActive = 'var(--alf-info-soft-active, #2293ad40)',

  LightSoft = 'var(--alf-light-soft, #f8f9fa)',
  LightSoftBorder = 'var(--alf-light-soft-border, #e9ecef)',
  LightSoftBorderHover = 'var(--alf-light-soft-border-hover, #dee2e6)',
  LightSoftHover = 'var(--alf-light-soft-hover, #f4f5f7)',
  LightSoftText = 'var(--alf-light-soft-text, #212529)',
  LightSoftTextHover = 'var(--alf-light-soft-text-hover, #212529)',
  LightSoftFocus = 'var(--alf-light-soft-focus, #21252940)',
  LightSoftDisabled = 'var(--alf-light-soft-disabled, #f4f5f6)',
  LightSoftActive = 'var(--alf-light-soft-active, #21252940)',

  DarkSoft = 'var(--alf-dark-soft, #e9ecef)',
  DarkSoftBorder = 'var(--alf-dark-soft-border, #dee2e6)',
  DarkSoftBorderHover = 'var(--alf-dark-soft-border-hover, #ced4da)',
  DarkSoftHover = 'var(--alf-dark-soft-hover, #e6e9ec)',
  DarkSoftText = 'var(--alf-dark-soft-text, #6c757d)',
  DarkSoftTextHover = 'var(--alf-dark-soft-text-hover, #495057)',
  DarkSoftFocus = 'var(--alf-dark-soft-focus, #49505740)',
  DarkSoftDisabled = 'var(--alf-dark-soft-disabled, #c0c2c4)',
  DarkSoftActive = 'var(--alf-dark-soft-active, #343a4040)',

  // ===== 3D MODALITY =====
  Primary3D = 'var(--alf-primary-3d, linear-gradient(to bottom, #4ea1fd, #0d6efd))',
  Primary3DHover = 'var(--alf-primary-3d-hover, linear-gradient(to bottom, #0d6efd, #0a58ca))',
  Primary3DFocus = 'var(--alf-primary-3d-focus, linear-gradient(to bottom, #0d6efd, #0a58ca))',
  Primary3DText = 'var(--alf-primary-3d-text, #ffffffff)',
  Primary3DTextHover = 'var(--alf-primary-3d-text-hover, #d1d1d1ff)',
  Primary3DDisabled = 'var(--alf-primary-3d-disabled, #b6cbf2)',
  Primary3DActive = 'var(--alf-primary-3d-active, #0a58ca)',

  Secondary3D = 'var(--alf-secondary-3d, linear-gradient(to bottom, #8a9197, #6c757d))',
  Secondary3DHover = 'var(--alf-secondary-3d-hover, linear-gradient(to bottom, #6c757d, #5a6268))',
  Secondary3DFocus = 'var(--alf-secondary-3d-focus, linear-gradient(to bottom, #6c757d, #5a6268))',
  Secondary3DText = 'var(--alf-secondary-3d-text, #ffffffff)',
  Secondary3DTextHover = 'var(--alf-secondary-3d-text-hover, #d1d1d1ff)',
  Secondary3DDisabled = 'var(--alf-secondary-3d-disabled, #c4c8cb)',
  Secondary3DActive = 'var(--alf-secondary-3d-active, linear-gradient(to bottom, #5a6268, #4e555b))',

  Success3D = 'var(--alf-success-3d, linear-gradient(to bottom, #28a745, #198754))',
  Success3DHover = 'var(--alf-success-3d-hover, linear-gradient(to bottom, #198754, #157347))',
  Success3DFocus = 'var(--alf-success-3d-focus, linear-gradient(to bottom, #198754, #157347))',
  Success3DText = 'var(--alf-success-3d-text, #ffffffff)',
  Success3DTextHover = 'var(--alf-success-3d-text-hover, #d1d1d1ff)',
  Success3DDisabled = 'var(--alf-success-3d-disabled, #b3d7c4)',
  Success3DActive = 'var(--alf-success-3d-active, linear-gradient(to bottom, #157347, #115c3a))',

  Danger3D = 'var(--alf-danger-3d, linear-gradient(to bottom, #e35d6a, #dc3545))',
  Danger3DHover = 'var(--alf-danger-3d-hover, linear-gradient(to bottom, #dc3545, #bb2d3b))',
  Danger3DFocus = 'var(--alf-danger-3d-focus, linear-gradient(to bottom, #dc3545, #bb2d3b))',
  Danger3DText = 'var(--alf-danger-3d-text, #ffffffff)',
  Danger3DTextHover = 'var(--alf-danger-3d-text-hover, #d1d1d1ff)',
  Danger3DDisabled = 'var(--alf-danger-3d-disabled, #f1b8be)',
  Danger3DActive = 'var(--alf-danger-3d-active, linear-gradient(to bottom, #bb2d3b, #a52834))',

  Warning3D = 'var(--alf-warning-3d, linear-gradient(to bottom, #ffcd39, #ffc107))',
  Warning3DHover = 'var(--alf-warning-3d-hover, linear-gradient(to bottom, #ffc107, #ffca2c))',
  Warning3DFocus = 'var(--alf-warning-3d-focus, linear-gradient(to bottom, #ffc107, #ffca2c))',
  Warning3DText = 'var(--alf-warning-3d-text, #565656ff)',
  Warning3DTextHover = 'var(--alf-warning-3d-text-hover, #565656ff))',
  Warning3DDisabled = 'var(--alf-warning-3d-disabled, #fce59f)',
  Warning3DActive = 'var(--alf-warning-3d-active, linear-gradient(to bottom, #ffca2c, #e0a800))',

  Info3D = 'var(--alf-info-3d, linear-gradient(to bottom, #39d9fa, #0dcaf0))',
  Info3DHover = 'var(--alf-info-3d-hover, linear-gradient(to bottom, #0dcaf0, #31d2f2))',
  Info3DFocus = 'var(--alf-info-3d-focus, linear-gradient(to bottom, #0dcaf0, #31d2f2))',
  Info3DText = 'var(--alf-warning-3d-text, #565656ff)',
  Info3DTextHover = 'var(--alf-warning-3d-text-hover, #565656ff))',
  Info3DDisabled = 'var(--alf-info-3d-disabled, #abecf7)',
  Info3DActive = 'var(--alf-info-3d-active, linear-gradient(to bottom, #31d2f2, #0baccc))',

  Light3D = 'var(--alf-light-3d, linear-gradient(to bottom, #ffffff, #f8f9fa))',
  Light3DHover = 'var(--alf-light-3d-hover, linear-gradient(to bottom, #f8f9fa, #e9ecef))',
  Light3DFocus = 'var(--alf-light-3d-focus, linear-gradient(to bottom, #f8f9fa, #e9ecef))',
  Light3DText = 'var(--alf-light-3d-text, #ffffffff)',
  Light3DTextHover = 'var(--alf-light-3d-text-hover, #d1d1d1ff)',
  Light3DDisabled = 'var(--alf-light-3d-disabled, #eef0f2)',
  Light3DActive = 'var(--alf-light-3d-active, linear-gradient(to bottom, #e9ecef, #dee2e6))',

  Dark3D = 'var(--alf-dark-3d, linear-gradient(to bottom, #343a40, #212529))',
  Dark3DHover = 'var(--alf-dark-3d-hover, linear-gradient(to bottom, #212529, #1c1f23))',
  Dark3DFocus = 'var(--alf-dark-3d-focus, linear-gradient(to bottom, #212529, #1c1f23))',
  Dark3DText = 'var(--alf-dark-3d-text, #ffffffff)',
  Dark3DTextHover = 'var(--alf-dark-3d-text-hover, #d1d1d1ff)',
  Dark3DDisabled = 'var(--alf-dark-3d-disabled, #aab0b4)',
  Dark3DActive = 'var(--alf-dark-3d-active, linear-gradient(to bottom, #1c1f23, #0f0f0f))',
`;
content = content.replace(/\n\}\s*$/, toInsert + '\n}\n');
fs.writeFileSync(file, content);
