export enum AlfVisualPredefinedEnum {
  SolidPrimary = 'solid-primary',
  SolidSecondary = 'solid-secondary',
  SolidSuccess = 'solid-success',
  SolidDanger = 'solid-danger',
  SolidWarning = 'solid-warning',
  SolidInfo = 'solid-info',
  SolidLight = 'solid-light',
  SolidDark = 'solid-dark',
  SolidDefault = 'solid-default',
  OutlinedPrimary = 'outlined-primary',
  OutlinedSecondary = 'outlined-secondary',
  OutlinedSuccess = 'outlined-success',
  OutlinedDanger = 'outlined-danger',
  OutlinedWarning = 'outlined-warning',
  OutlinedInfo = 'outlined-info',
  OutlinedLight = 'outlined-light',
  OutlinedDark = 'outlined-dark',
  OutlinedDefault = 'outlined-default',
}
