/**
 * Enum para iconos de ropa y moda
 * Catálogo extenso optimizado para aplicaciones de e-commerce de moda.
 * Permite tipificar categorías de productos de forma precisa.
 * 
 * @example
 * ```typescript
 * // En un componente Angular
 * category: AlfClothingIconTypeEnum.Tshirt // Referencia a camiseta básica
 * ```
 */
export enum AlfClothingIconTypeEnum {
  // Tops Básicos
  Tshirt = 'tshirt',
  Shirt = 'shirt',
  Polo = 'polo',
  Blouse = 'blouse',
  TankTop = 'tanktop',
  CropTop = 'croptop',
  Sweater = 'sweater',
  Cardigan = 'cardigan',
  Hoodie = 'hoodie',
  Vest = 'vest',
  Jacket = 'jacket',
  Coat = 'coat',
  Tunic = 'tunic',
  Henley = 'henley',
  LongSleeve = 'longsleeve',
  Turtleneck = 'turtleneck',
  VNeck = 'vneck',
  CrewNeck = 'crewneck',
  Sweatshirt = 'sweatshirt',
  Pullover = 'pullover',
  Poncho = 'poncho',
  Shawl = 'shawl',
  Bolero = 'bolero',
  Camisole = 'camisole',
  Halter = 'halter',
  OffShoulder = 'offshoulder',
  Peplum = 'peplum',
  Wrap = 'wrap',

  // Pantalones y Bottoms
  Pants = 'pants',
  Jeans = 'jeans',
  Leggings = 'leggings',
  Joggers = 'joggers',
  Chinos = 'chinos',
  CargoPants = 'cargopants',
  Shorts = 'shorts',
  Culottes = 'culottes',
  Capris = 'capris',
  Bermudas = 'bermudas',
  Trousers = 'trousers',
  Slacks = 'slacks',
  Overalls = 'overalls',
  Dungarees = 'dungarees',

  // Faldas
  Skirt = 'skirt',
  MiniSkirt = 'miniskirt',
  MaxiSkirt = 'maxiskirt',
  PencilSkirt = 'pencilskirt',
  ALineSkirt = 'alineskirt',
  PleatSkirt = 'pleatskirt',
  WrapSkirt = 'wrapskirt',
  TieredSkirt = 'tieredskirt',

  // Vestidos
  Dress = 'dress',
  DressFormal = 'dressformal',
  Sundress = 'sundress',
  Maxi = 'maxi',
  Midi = 'midi',
  ShirtDress = 'shirtdress',
  WrapDress = 'wrapdress',
  ShiftDress = 'shiftdress',
  BodyconDress = 'bodycondress',
  ALineDress = 'alinedress',
  EmpireDress = 'empiredress',
  BallGown = 'ballgown',
  CocktailDress = 'cocktaildress',
  EveningGown = 'eveninggown',

  // Conjuntos
  Jumpsuit = 'jumpsuit',
  Romper = 'romper',

  // Calzado
  Shoes = 'shoes',
  Sneakers = 'sneakers',
  Boots = 'boots',
  AnkleBoots = 'ankleboots',
  HikingBoots = 'hikingboots',
  Sandals = 'sandals',
  FlipFlops = 'flipflops',
  Heels = 'heels',
  Loafers = 'loafers',
  Slippers = 'slippers',
  Oxfords = 'oxfords',
  Brogues = 'brogues',
  Derbys = 'derbys',
  Moccasins = 'moccasins',
  Espadrilles = 'espadrilles',
  Wedges = 'wedges',
  Platforms = 'platforms',
  Stilettos = 'stilettos',
  Kitten = 'kitten',
  Pumps = 'pumps',
  Flats = 'flats',
  BalletFlats = 'balletflats',
  Clogs = 'clogs',
  Crocs = 'crocs',
  Wellies = 'wellies',
  CombatBoots = 'combatboots',
  ChelseaBoots = 'chelseaboots',
  CowboyBoots = 'cowboyboots',
  RidingBoots = 'ridingboots',
  SnowBoots = 'snowboots',

  // Accesorios - Cabeza
  Hat = 'hat',
  Cap = 'cap',
  Beanie = 'beanie',
  Bandana = 'bandana',
  Headband = 'headband',
  Beret = 'beret',
  Fedora = 'fedora',
  Panama = 'panama',
  Trilby = 'trilby',
  BucketHat = 'buckethat',
  Visor = 'visor',
  Turban = 'turban',
  Hijab = 'hijab',

  // Accesorios - Cuello y Manos
  Scarf = 'scarf',
  Gloves = 'gloves',
  Mittens = 'mittens',
  Belt = 'belt',
  Tie = 'tie',
  Bowtie = 'bowtie',
  TieClip = 'tieclip',
  Cufflinks = 'cufflinks',

  // Accesorios - Varios
  Umbrella = 'umbrella',
  Mask = 'mask',
  Bow = 'bow',
  Ribbon = 'ribbon',
  Brooch = 'brooch',
  Pin = 'pin',
  Badge = 'badge',
  Patch = 'patch',
  Suspenders = 'suspenders',
  Garter = 'garter',

  // Bolsos y Carteras
  Bag = 'bag',
  Backpack = 'backpack',
  Purse = 'purse',
  ToteBag = 'totebag',
  Clutch = 'clutch',
  MessengerBag = 'messengerbag',
  DuffelBag = 'duffelbag',
  Suitcase = 'suitcase',
  Wallet = 'wallet',
  Crossbody = 'crossbody',
  Satchel = 'satchel',
  Hobo = 'hobo',
  Bucket = 'bucketbag',
  Wristlet = 'wristlet',
  Fanny = 'fanny',
  BeltBag = 'beltbag',
  Briefcase = 'briefcase',
  LaptopBag = 'laptopbag',
  GymBag = 'gymbag',
  WeekenderBag = 'weekenderbag',
  CarryOn = 'carryon',
  TravelBag = 'travelbag',
  GarmentBag = 'garmentbag',
  CosmeticBag = 'cosmeticbag',
  Pouch = 'pouch',
  Clutch2 = 'clutch2',
  Minaudiere = 'minaudiere',

  // Gafas y Relojes
  Sunglasses = 'sunglasses',
  Glasses = 'glasses',
  Watch = 'watch',

  // Joyería
  Jewelry = 'jewelry',
  Ring = 'ring',
  Necklace = 'necklace',
  Earrings = 'earrings',
  Bracelet = 'bracelet',
  Anklet = 'anklet',
  ChainNecklace = 'chainnecklace',
  PendantNecklace = 'pendantnecklace',
  ChokerNecklace = 'chokernecklace',
  StudEarrings = 'studearrings',
  HoopEarrings = 'hoopearrings',
  DropEarrings = 'dropearrings',
  BanglesBracelet = 'banglesbracelet',
  CharmBracelet = 'charmbracelet',
  CuffBracelet = 'cuffbracelet',
  EngagementRing = 'engagementring',
  WeddingBand = 'weddingband',
  CocktailRing = 'cocktailring',

  // Ropa Interior y Dormir
  Socks = 'socks',
  Underwear = 'underwear',
  Bra = 'bra',
  Pajamas = 'pajamas',
  Robe = 'robe',
  Nightgown = 'nightgown',

  // Ropa Deportiva
  Sportswear = 'sportswear',
  Gym = 'gym',
  Running = 'running',
  YogaPants = 'yogapants',
  SportsBra = 'sportsbra',
  TrackPants = 'trackpants',
  TrackJacket = 'trackjacket',
  Windsuit = 'windsuit',
  Compression = 'compression',
  CyclingShorts = 'cyclingshorts',
  RunningShorts = 'runningshorts',
  BoardShorts = 'boardshorts',
  RashGuard = 'rashguard',
  Wetsuit = 'wetsuit',
  SkiJacket = 'skijacket',
  SkiPants = 'skipants',
  BaseLayer = 'baselayer',
  ThermalTop = 'thermaltop',
  ThermalBottom = 'thermalbottom',
  JerseyTop = 'jerseytop',
  TankJersey = 'tankjersey',

  // Ropa Formal
  Suit = 'suit',
  Tuxedo = 'tuxedo',
  Blazer = 'blazer',
  MorningCoat = 'morningcoat',
  TailCoat = 'tailcoat',
  DinnerJacket = 'dinnerjacket',
  Waistcoat = 'waistcoat',
  CummerbundBelt = 'cummerbundbelt',
  DressPants = 'dresspants',
  DressShirt = 'dressshirt',
  FrenchCuff = 'frenchcuff',
  WingCollar = 'wingcollar',
  Ascot = 'ascot',
  PocketSquare = 'pocketsquare',

  // Ropa Casual
  GraphicTee = 'graphictee',
  StripedShirt = 'stripedshirt',
  PlaidShirt = 'plaidshirt',
  FlannelShirt = 'flannelshirt',
  ChambraShirt = 'chambrashirt',
  UtilityJacket = 'utilityjacket',
  ShacketJacket = 'shacketjacket',
  CargoShorts = 'cargoshorts',
  DenimShorts = 'denimshorts',
  SweatShorts = 'sweatshorts',

  // Trajes de Baño
  Swimsuit = 'swimsuit',
  Bikini = 'bikini',
  SwimTrunks = 'swimtrunks',

  // Ropa de Abrigo
  WinterCoat = 'wintercoat',
  Raincoat = 'raincoat',
  Parka = 'parka',
  Trench = 'trench',
  Peacoat = 'peacoat',
  Bomber = 'bomber',
  Denim = 'denim',
  Leather = 'leather',
  Windbreaker = 'windbreaker',
  Anorak = 'anorak',
  Puffer = 'puffer',
  Fleece = 'fleece',
  Gilet = 'gilet',

  // Ropa Infantil
  Onesie = 'onesie',
  Bib = 'bib',
  Diaper = 'diaper',
  KidsShirt = 'kidsshirt',

  // E-commerce y Tienda
  Hanger = 'hanger',
  SaleTag = 'saletag',
  NewArrival = 'newarrival',
  ShoppingCart = 'shoppingcart',
  Wishlist = 'wishlist',
  SizeGuide = 'sizeguide',
  WashCare = 'washcare',
  GiftCard = 'giftcard',
}
