import { SupportedLanguage } from '../helpers/i18n.helper';

/**
 * Teclas para etiquetas globales y reutilizables en toda la aplicación.
 * Siguiendo el estándar del proyecto de usar Enums para todo.
 */
export enum AlfLabelEnum {
  ACCEPT = 'ACCEPT',
  CANCEL = 'CANCEL',
  SAVE = 'SAVE',
  DELETE = 'DELETE',
  EDIT = 'EDIT',
  CLOSE = 'CLOSE',
  CONFIRM = 'CONFIRM',
  BACK = 'BACK',
  SUBMIT = 'SUBMIT',
  LOADING = 'LOADING',
  INFO = 'INFO',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  SEARCH = 'SEARCH',
  NO_RESULTS = 'NO_RESULTS',
  CLEAR_SELECTION = 'CLEAR_SELECTION',
  SELECT_ALL = 'SELECT_ALL',
}

/**
 * Diccionario maestro de traducciones para las etiquetas globales.
 */
export const ALF_GLOBAL_TRANSLATIONS: Record<SupportedLanguage, Record<AlfLabelEnum, string>> = {
  es: {
    [AlfLabelEnum.ACCEPT]: 'Aceptar',
    [AlfLabelEnum.CANCEL]: 'Cancelar',
    [AlfLabelEnum.SAVE]: 'Guardar',
    [AlfLabelEnum.DELETE]: 'Eliminar',
    [AlfLabelEnum.EDIT]: 'Editar',
    [AlfLabelEnum.CLOSE]: 'Cerrar',
    [AlfLabelEnum.CONFIRM]: 'Confirmar',
    [AlfLabelEnum.BACK]: 'Volver',
    [AlfLabelEnum.SUBMIT]: 'Enviar',
    [AlfLabelEnum.LOADING]: 'Cargando...',
    [AlfLabelEnum.INFO]: 'Información',
    [AlfLabelEnum.WARNING]: 'Advertencia',
    [AlfLabelEnum.ERROR]: 'Error',
    [AlfLabelEnum.SUCCESS]: 'Éxito',
    [AlfLabelEnum.SEARCH]: 'Buscar...',
    [AlfLabelEnum.NO_RESULTS]: 'Sin resultados',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Limpiar selección',
    [AlfLabelEnum.SELECT_ALL]: 'Seleccionar todo',
  },
  en: {
    [AlfLabelEnum.ACCEPT]: 'Accept',
    [AlfLabelEnum.CANCEL]: 'Cancel',
    [AlfLabelEnum.SAVE]: 'Save',
    [AlfLabelEnum.DELETE]: 'Delete',
    [AlfLabelEnum.EDIT]: 'Edit',
    [AlfLabelEnum.CLOSE]: 'Close',
    [AlfLabelEnum.CONFIRM]: 'Confirm',
    [AlfLabelEnum.BACK]: 'Back',
    [AlfLabelEnum.SUBMIT]: 'Submit',
    [AlfLabelEnum.LOADING]: 'Loading...',
    [AlfLabelEnum.INFO]: 'Information',
    [AlfLabelEnum.WARNING]: 'Warning',
    [AlfLabelEnum.ERROR]: 'Error',
    [AlfLabelEnum.SUCCESS]: 'Success',
    [AlfLabelEnum.SEARCH]: 'Search...',
    [AlfLabelEnum.NO_RESULTS]: 'No results found',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Clear selection',
    [AlfLabelEnum.SELECT_ALL]: 'Select all',
  },
  fr: {
    [AlfLabelEnum.ACCEPT]: 'Accepter',
    [AlfLabelEnum.CANCEL]: 'Annuler',
    [AlfLabelEnum.SAVE]: 'Enregistrer',
    [AlfLabelEnum.DELETE]: 'Supprimer',
    [AlfLabelEnum.EDIT]: 'Modifier',
    [AlfLabelEnum.CLOSE]: 'Fermer',
    [AlfLabelEnum.CONFIRM]: 'Confirmer',
    [AlfLabelEnum.BACK]: 'Retour',
    [AlfLabelEnum.SUBMIT]: 'Envoyer',
    [AlfLabelEnum.LOADING]: 'Chargement...',
    [AlfLabelEnum.INFO]: 'Information',
    [AlfLabelEnum.WARNING]: 'Avertissement',
    [AlfLabelEnum.ERROR]: 'Erreur',
    [AlfLabelEnum.SUCCESS]: 'Succès',
    [AlfLabelEnum.SEARCH]: 'Rechercher...',
    [AlfLabelEnum.NO_RESULTS]: 'Aucun résultat',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Effacer la sélection',
    [AlfLabelEnum.SELECT_ALL]: 'Tout sélectionner',
  },
  de: {
    [AlfLabelEnum.ACCEPT]: 'Akzeptieren',
    [AlfLabelEnum.CANCEL]: 'Abbrechen',
    [AlfLabelEnum.SAVE]: 'Speichern',
    [AlfLabelEnum.DELETE]: 'Löschen',
    [AlfLabelEnum.EDIT]: 'Bearbeiten',
    [AlfLabelEnum.CLOSE]: 'Schließen',
    [AlfLabelEnum.CONFIRM]: 'Bestätigen',
    [AlfLabelEnum.BACK]: 'Zurück',
    [AlfLabelEnum.SUBMIT]: 'Absenden',
    [AlfLabelEnum.LOADING]: 'Laden...',
    [AlfLabelEnum.INFO]: 'Information',
    [AlfLabelEnum.WARNING]: 'Warnung',
    [AlfLabelEnum.ERROR]: 'Fehler',
    [AlfLabelEnum.SUCCESS]: 'Erfolg',
    [AlfLabelEnum.SEARCH]: 'Suche...',
    [AlfLabelEnum.NO_RESULTS]: 'Keine Ergebnisse',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Auswahl aufheben',
    [AlfLabelEnum.SELECT_ALL]: 'Alle auswählen',
  },
  it: {
    [AlfLabelEnum.ACCEPT]: 'Accetta',
    [AlfLabelEnum.CANCEL]: 'Annulla',
    [AlfLabelEnum.SAVE]: 'Salva',
    [AlfLabelEnum.DELETE]: 'Elimina',
    [AlfLabelEnum.EDIT]: 'Modifica',
    [AlfLabelEnum.CLOSE]: 'Chiudi',
    [AlfLabelEnum.CONFIRM]: 'Conferma',
    [AlfLabelEnum.BACK]: 'Indietro',
    [AlfLabelEnum.SUBMIT]: 'Invia',
    [AlfLabelEnum.LOADING]: 'Caricamento...',
    [AlfLabelEnum.INFO]: 'Informazione',
    [AlfLabelEnum.WARNING]: 'Avvertimento',
    [AlfLabelEnum.ERROR]: 'Errore',
    [AlfLabelEnum.SUCCESS]: 'Successo',
    [AlfLabelEnum.SEARCH]: 'Cerca...',
    [AlfLabelEnum.NO_RESULTS]: 'Nessun risultato',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Cancella selezione',
    [AlfLabelEnum.SELECT_ALL]: 'Seleziona tutto',
  },
  pt: {
    [AlfLabelEnum.ACCEPT]: 'Aceitar',
    [AlfLabelEnum.CANCEL]: 'Cancelar',
    [AlfLabelEnum.SAVE]: 'Salvar',
    [AlfLabelEnum.DELETE]: 'Excluir',
    [AlfLabelEnum.EDIT]: 'Editar',
    [AlfLabelEnum.CLOSE]: 'Fechar',
    [AlfLabelEnum.CONFIRM]: 'Confirmar',
    [AlfLabelEnum.BACK]: 'Voltar',
    [AlfLabelEnum.SUBMIT]: 'Enviar',
    [AlfLabelEnum.LOADING]: 'Carregando...',
    [AlfLabelEnum.INFO]: 'Informação',
    [AlfLabelEnum.WARNING]: 'Aviso',
    [AlfLabelEnum.ERROR]: 'Erro',
    [AlfLabelEnum.SUCCESS]: 'Sucesso',
    [AlfLabelEnum.SEARCH]: 'Buscar...',
    [AlfLabelEnum.NO_RESULTS]: 'Nenhum resultado',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Limpar seleção',
    [AlfLabelEnum.SELECT_ALL]: 'Selecionar tudo',
  },
  ru: {
    [AlfLabelEnum.ACCEPT]: 'Принять',
    [AlfLabelEnum.CANCEL]: 'Отмена',
    [AlfLabelEnum.SAVE]: 'Сохранить',
    [AlfLabelEnum.DELETE]: 'Удалить',
    [AlfLabelEnum.EDIT]: 'Редактировать',
    [AlfLabelEnum.CLOSE]: 'Закрыть',
    [AlfLabelEnum.CONFIRM]: 'Подтвердить',
    [AlfLabelEnum.BACK]: 'Назад',
    [AlfLabelEnum.SUBMIT]: 'Отправить',
    [AlfLabelEnum.LOADING]: 'Загрузка...',
    [AlfLabelEnum.INFO]: 'Информация',
    [AlfLabelEnum.WARNING]: 'Предупреждение',
    [AlfLabelEnum.ERROR]: 'Ошибка',
    [AlfLabelEnum.SUCCESS]: 'Успех',
    [AlfLabelEnum.SEARCH]: 'Поиск...',
    [AlfLabelEnum.NO_RESULTS]: 'Нет результатов',
    [AlfLabelEnum.CLEAR_SELECTION]: 'Очистить выбор',
    [AlfLabelEnum.SELECT_ALL]: 'Выбрать все',
  },
};
